
#define ATT_CID 4

/*UUID of Gap and ESS service */

#define UUID_GAP 0x1800
#define UUID_ESS_SERVICE 0x181A

/*UUID's of all the ESS characteristics */

#define UUID_TEMPERATURE 0x2A6E
#define UUID_APPARENT_WIND_SPEED 0x2A72
#define UUID_APPARENT_WIND_DIRECTION 0x2A73
#define UUID_DEW_POINT 0x2A7B
#define UUID_ELEVATION 0x2A6C
#define UUID_GUST_FACTOR 0x2A74
#define UUID_HEAT_INDEX 0x2A7A
#define UUID_HUMIDITY 0x2A6F
#define UUID_IRRADIANCE 0x2A77
#define UUID_POLLEN_CONCENTRATION 0x2A75
#define UUID_RAIN_FALL 0x2A78
#define UUID_PRESSURE 0x2A6D
#define UUID_TRUE_WIND_DIRECTION 0x2A71
#define UUID_TRUE_WIND_SPEED 0x2A70
#define UUID_UV_INDEX 0x2A76
#define UUID_WIND_CHILL 0x2A79
#define UUID_BAROMETRIC_PRESSURE_TREND 0x2AA3
#define UUID_MAGNETIC_DECLINATION 0x2A2C
#define UUID_MAGNETIC_FLUX_DENSITY_2D 0x2AA0
#define UUID_MAGNETIC_FLUX_DENSITY_3D 0x2AA1

/*UUID's of all the descriptors supported by ESS */

#define ESS_MEASUREMENT_DESC 0x290C
#define ESS_TRIGER_DESC 0x290D
#define ESS_VALID_RANGE_DESC 0x2906
#define ESS_CHAR_USER_DESC 0x2901
#define CLIENT_CHARAC_CFG_UUID 0x2902
